<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-D34DC2QJ" name="com.busyqa.test.TestCases.TC05_FailedTC" tests="2" failures="0" timestamp="2020-06-06T15:58:58 IST" time="6.075" errors="1">
  <testcase name="failedTest" time="0.000" classname="com.busyqa.test.TestCases.TC05_FailedTC">
    <skipped/>
  </testcase> <!-- failedTest -->
  <system-out/>
  <testcase name="setUp" time="6.075" classname="com.busyqa.test.TestCases.TC05_FailedTC">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.busyqa.test.TestBase.TestBase.selectBrowser(TestBase.java:34)
at com.busyqa.test.TestBase.TestBase.init(TestBase.java:21)
at com.busyqa.test.TestCases.TC05_FailedTC.setUp(TC05_FailedTC.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619)
at org.testng.TestRunner.beforeRun(TestRunner.java:609)
at org.testng.TestRunner.run(TestRunner.java:580)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
</testsuite> <!-- com.busyqa.test.TestCases.TC05_FailedTC -->
